FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Shanghai
ENV TERM=xterm-256color
ENV PIP_INDEX_URL=https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple

# base dependencies
RUN sed -E -i "s/(archive|security).ubuntu.com/mirrors.tuna.tsinghua.edu.cn/g" /etc/apt/sources.list && \
    apt-get update && apt-get upgrade -y && \
    apt-get install -y \
    nano vim tzdata curl wget ca-certificates gnupg lsb-release \
    build-essential pkg-config ninja-build git \
    meson libglib2.0-dev libpixman-1-dev zlib1g-dev \
    libslirp-dev libsdl2-dev libaio-dev libcap-dev \
    libiscsi-dev libnfs-dev libseccomp-dev \
    python3 python3-pip python-is-python3 \
    openssh-server && \
    rm -rf /var/lib/apt/lists/*

# SSH setup
RUN mkdir -p /var/run/sshd && \
    mkdir -p /root/.ssh && chmod 700 /root/.ssh

COPY id_rsa.pub /root/.ssh/authorized_keys
RUN chmod 600 /root/.ssh/authorized_keys

# User setup prep.
RUN mkdir -p /root/setup
COPY setup_users.sh /root/setup/
COPY users.csv.template /root/setup/
RUN chmod +x /root/setup/setup_users.sh

# SSH hardening
RUN echo "PasswordAuthentication no" >> /etc/ssh/sshd_config && \
    echo "PermitRootLogin prohibit-password" >> /etc/ssh/sshd_config && \
    echo "PubkeyAuthentication yes" >> /etc/ssh/sshd_config

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
